apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-api-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: author-api-pod
  template:
    metadata:
      labels:
        app: author-api-pod
    spec:
      containers:
        - name: author-api-container
          image: __DOCKER_IMAGE__
          ports:
            - name: author-api-cp
              containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: RABBIT_MQ_HOST
              value: rabbitmq-cluster-ip
            - name: RABBIT_MQ_PASSWORD
              value: rabbitmq
            - name: RABBIT_MQ_USERNAME
              value: rabbitmq
            - name: DB_HOST
              value: author-api-mysql-cluster-ip
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: prod
            - name: DB_USER
              value: mysql
            - name: DB_PASSWORD
              value: thisIsReallyStrongPassword123
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: author-api-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: author-api-pod
  ports:
    - name: author-api-cip
      port: 80
      targetPort: author-api-cp
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: author-api-node-port
spec:
  type: NodePort
  selector:
    app: author-api-pod
  ports:
    - name: author-api-np
      protocol: TCP
      port: 80
      targetPort: author-api-cp
      # not need to set
      nodePort: 32222
