server:
  port: ${PORT:7070}

spring:
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2dll:
          create_namespaces: true

  rabbitmq:
    host: ${RABBIT_MQ_HOST:rabbitMQ}
    port: 5672
    password: ${RABBIT_MQ_PASSWORD:rabbitmq}
    username: ${RABBIT_MQ_USERNAME:rabbitmq}

  datasource:
    url: jdbc:mysql://${DB_HOST:book-api-mysql}:${DB_PORT:3306}/${DB_NAME:dev}?createDatabaseIfNotExist=true
    username: ${DB_USER:mysql}
    password: ${DB_PASSWORD:thisIsReallyStrongPassword123}
    driver-class-name: com.mysql.cj.jdbc.Driver
