version: "3.9"

services:
  workspace:
    container_name: ${PROJECT_NAME:-default}-workspace-container
    build:
      context: ./docker/workspace
      args:
        USERNAME: ${USERNAME:-vscode}
        USER_GROUP_NAME: ${USER_GROUP_NAME:-workspace}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    tty: true

    volumes:
      - ../:/home/${USERNAME:-vscode}/workspace:cached
    working_dir: /workspace

  author-api-mysql:
    container_name: ${PROJECT_NAME:-default}-author-api-mysql-container
    restart: unless-stopped
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      # - ./docker/mysql/init-tables.sql:/docker-entrypoint-initdb.d/init-tables.sql
      - ./.docker/author_api_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTHOR_API_DB_ROOT_PASSWORD:-thisIsReallyStrongPassword123}
      MYSQL_DATABASE: ${AUTHOR_API_DB_DATABASE:-dev}
      MYSQL_USER: ${AUTHOR_API_DB_USER:-mysql}
      MYSQL_PASSWORD: ${AUTHOR_API_DB_PASSWORD:-thisIsReallyStrongPassword123}

  book-api-mysql:
    container_name: ${PROJECT_NAME:-default}-book-api-mysql-container
    restart: unless-stopped
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT:-3305}:3306
    volumes:
      # - ./docker/mysql/init-tables.sql:/docker-entrypoint-initdb.d/init-tables.sql
      - ./.docker/book_api_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${BOOK_API_DB_ROOT_PASSWORD:-thisIsReallyStrongPassword123}
      MYSQL_DATABASE: ${BOOK_API_DB_DATABASE:-dev}
      MYSQL_USER: ${BOOK_API_DB_USER:-mysql}
      MYSQL_PASSWORD: ${BOOK_API_DB_PASSWORD:-thisIsReallyStrongPassword123}

  rabbitMQ:
    image: rabbitmq:3.9.13-management-alpine
    container_name: ${PROJECT_NAME:-default}-rabbitMQ-container
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.docker/rabbitmqdata:/var/lib/rabbitmq
      - ./.docker/rabbitmqlog:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-rabbitmq}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-rabbitmq}

  nginx:
    build:
      context: ./docker/nginx
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-default}-nginx-container
    ports:
      - 3333:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
